--Table : Log(LogMessage varchar(100), logDate Datetime) 
--Part – A 
--1. Create trigger for blocking student deletion.
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_STUDENT_DELETE
ON STUDENT
INSTEAD OF DELETE
AS BEGIN
	PRINT 'STUDENT NOT ALLOW TO DELETE'
END

DROP TRIGGER TR_INSTEAD_OF_STUDENT_DELETE

--2. Create trigger for making course read-only. 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_COURSE_READ_ONLY
ON COURSE1
INSTEAD OF INSERT,UPDATE,DELETE
AS BEGIN
	PRINT 'MAKING COURSE READ-ONLY'
END

DROP TRIGGER TR_INSTEAD_OF_COURSE_READ_ONLY

--3. Create trigger for preventing faculty removal.
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_FACULTY_DELETE
ON FACULTY
INSTEAD OF DELETE
AS BEGIN
	PRINT 'FACULTY NOT ALLOW TO DELETE'
END

DROP TRIGGER TR_INSTEAD_OF_FACULTY_DELETE

--4. Create instead of trigger to log all operations on COURSE (INSERT/UPDATE/DELETE) into Log table. 
--(Example: INSERT/UPDATE/DELETE operations are blocked for you in course table) 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_COURSE_OPERATION
ON COURSE1
INSTEAD OF INSERT,UPDATE,DELETE
AS BEGIN
	INSERT INTO LOG VALUES ('INSERT/UPDATE/DELETE operations are blocked for you in course table', GETDATE())
END

DROP TRIGGER TR_INSTEAD_OF_COURSE_OPERATION

--5. Create trigger to Block student to update their enrollment year and print message ‘students are not 
--allowed to update their enrollment year’ 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_STUDENT_UPDATE_ENYEAR
ON STUDENT
INSTEAD OF UPDATE
AS BEGIN
	PRINT 'students are not allowed to update their enrollment year'
END

DROP TRIGGER TR_INSTEAD_OF_STUDENT_UPDATE_ENYEAR

--6. Create trigger for student age validation (Min 18). 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_STUDENT_AGE_VALIDATION
ON STUDENT
INSTEAD OF INSERT
AS BEGIN
	DECLARE @AGE INT, @DOB DATE
	SELECT @DOB = StuDateOfBirth FROM inserted
	SET @AGE = DATEDIFF(YEAR,@DOB, GETDATE())

	IF @AGE < 18
		BEGIN
			PRINT 'STUDENT AGE VALIDATION(MIN 18)'
		END
	ELSE
		BEGIN
			INSERT INTO STUDENT(StudentID,StuEmail,StuPhone,StuDepartment,StuDateOfBirth,StuEnrollmentYear,CGPA)
			SELECT StudentID,StuEmail,StuPhone,StuDepartment,StuDateOfBirth,StuEnrollmentYear,CGPA FROM inserted
		END
END

DROP TRIGGER TR_INSTEAD_OF_STUDENT_AGE_VALIDATION


--Part – B 
--7. Create trigger for unique faculty’s email check. 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_FACULTY_EMAIL_CHECK
ON FACULTY
INSTEAD OF INSERT
AS BEGIN
	IF EXISTS(SELECT 1 FROM FACULTY JOIN inserted ON FACULTY.FacultyEmail = inserted.FacultyEmail)
		BEGIN
			PRINT 'ADD UNIQUE EMAIL'
		END
	
	ELSE
		BEGIN
		INSERT INTO FACULTY SELECT * FROM inserted
		END
END

DROP TRIGGER TR_INSTEAD_OF_FACULTY_EMAIL_CHECK

--8. Create trigger for preventing duplicate enrollment. 
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_STUDENT_ENROLLMENT_CHECK
ON STUDENT
INSTEAD OF INSERT
AS BEGIN
	--IF EXISTS(SELECT 1 FROM STUDENT JOIN inserted ON STUDENT.StuEnrollmentYear = inserted.StuEnrollmentYear)
	--	BEGIN
	--		PRINT 'ADD UNIQUE ENROLLMENT'
	--	END
	
	--ELSE
	--	BEGIN
	--	INSERT INTO STUDENT SELECT * FROM inserted
	--	END
END

DROP TRIGGER TR_INSTEAD_OF_STUDENT_ENROLLMENT_CHECK


--Part - C 
--9. Create trigger to Allow enrolment in month from Jan to August, otherwise print message enrolment closed.
CREATE OR ALTER TRIGGER TR_INSTEAD_OF_ENROLLMENT
ON ENROLLMENT
INSTEAD OF INSERT
AS BEGIN
		DECLARE @MON INT
		SELECT @MON = MONTH(EnrollmentDate) FROM inserted
	IF @MON <= 8
		BEGIN
			INSERT INTO ENROLLMENT SELECT * FROM inserted
		END
	
	ELSE
		BEGIN
			PRINT 'NOT ALLOW'
		END
END

DROP TRIGGER TR_INSTEAD_OF_FACULTY_EMAIL_CHECK

--10. Create trigger to Allow only grade change in enrollment (block other updates)
CREATE OR ALTER TRIGGER TR_AFTER_ENROLLMENT_UPDATE_GRADE
ON ENROLLMENT
AFTER UPDATE
AS BEGIN
	DECLARE @OLD VARCHAR(10), @NEW VARCHAR(10), @ID INT
	SELECT @OLD = GRADE FROM deleted
	SELECT @NEW = GRADE FROM inserted
	SELECT @ID = EnrollmentID FROM inserted
	IF @OLD != @NEW
		BEGIN
			UPDATE ENROLLMENT
			SET Grade = @NEW
			WHERE EnrollmentID = @ID
		END
	ELSE
		BEGIN
			PRINT 'DO NOT ALLOW TO CHANGE ANOTHER COLOUMN'
		END
END

DROP TRIGGER TR_AFTER_ENROLLMENT_UPDATE_GRADE